camera/horizontal_fov: 114.59
camera/vertical_fov: 85.94

raycast/dr:     0.1
raycast/dphi:   10
raycast/dtheta: 10

system/bbx/r: 0.5
system/bbx/overshoot: 0.25

aep/gain/r_min: 0
aep/gain/r_max: 5
aep/gain/zero: 25
aep/gain/lambda: 0.75
aep/gain/sigma_thresh: 0.2
aep/tree/extension_range: 1
aep/tree/max_sampling_radius: 40
aep/tree/initial_iterations: 15
aep/tree/cutoff_iterations: 30

rrt/min_nodes: 100

# bounding box: necessary to limit the simulation 
# scenario (smaller than actual gazebo scenario)
boundary/min: [-2.5, -2.5, -0.1]
boundary/max: [40.0,  2.5, 12.0]

visualize_rays: false
visualize_tree: false
visualize_exploration_area: true

robot_frame: "firefly/base_link"
world_frame: "map"

